---
  - hosts: loadbalancer
    become: true
    tasks:
      - name: install_nginx
        apt: name=nginx state=present update_cache=yes

      - name: ensure_nginx_started
        service: name=nginx state=started enabled=yes
