---
  - hosts: webserver
    become: true
    tasks:
      - name: install_webserver_components
        apt: name={{item}} state=present update_cache=yes
        with_items:
          - apache2
          - libapache2-mod-wsgi
          - python-pip
          - python-virtualenv

      - name: ensure_apache_started
        service: name=apache2 state=started enabled=yes
